import { UserProfile, DemoPreset } from './types';

export const AVATAR_OPTIONS = [
  { id: 'chef', emoji: '👨‍🍳', label: 'Шеф', color: 'from-amber-400 to-orange-500' },
  { id: 'healthy', emoji: '🥑', label: 'Авокадо', color: 'from-emerald-400 to-teal-500' },
  { id: 'basket', emoji: '🧺', label: 'Корзина', color: 'from-blue-400 to-indigo-500' },
  { id: 'smart', emoji: '🦊', label: 'Лис', color: 'from-orange-400 to-red-500' },
  { id: 'coffee', emoji: '☕', label: 'Кофе', color: 'from-stone-500 to-stone-700' },
  { id: 'apple', emoji: '🍎', label: 'Яблоко', color: 'from-rose-400 to-pink-500' },
  { id: 'money', emoji: '💳', label: 'Бюджет', color: 'from-violet-400 to-purple-600' },
  { id: 'cat', emoji: '🐱', label: 'Кот', color: 'from-cyan-400 to-blue-500' },
];

export const DEFAULT_PROFILE: UserProfile = {
  currency: 'RUB',
  monthlyBudget: 35000,
  weeklyTarget: 8750,
  dailyTarget: 1166,
  adultsCount: 1,
  childrenCount: 0,
  petsCount: 0,
  dietaryPreferences: ['standard', 'healthy'],
  favoriteStores: ['pyaterochka', 'vkusvill', 'samokat'],
  budgetGoal: 'smart_planning',
  budgetGoals: ['smart_planning', 'save_money'],
  budgetAlertThreshold: 80,
  notificationSettings: {
    budgetAlerts: true,
    weeklyDigest: true,
    savingTips: true,
  },
  city: 'Москва',
  notes: 'Планируем закупаться раз в неделю и докупать свежее у дома',
  updatedAt: new Date().toISOString(),
};

export const DEMO_PRESETS: DemoPreset[] = [
  {
    id: 'demo-single',
    title: 'Один человек / Студент',
    subtitle: '1 взрослый • 18 000 ₽/мес • Разумная экономия',
    icon: '🎒',
    user: {
      id: 'demo-user-1',
      name: 'Алексей Смирнов',
      email: 'alex.student@budget.app',
      avatar: '🦊',
      avatarColor: 'from-orange-400 to-red-500',
      createdAt: '2026-08-15',
      isOnboarded: true,
      profile: {
        currency: 'RUB',
        monthlyBudget: 18000,
        weeklyTarget: 4500,
        dailyTarget: 600,
        adultsCount: 1,
        childrenCount: 0,
        petsCount: 0,
        dietaryPreferences: ['fitness', 'standard'],
        favoriteStores: ['pyaterochka', 'chizhik', 'samokat'],
        budgetGoal: 'save_money',
        budgetGoals: ['save_money', 'strict_budget'],
        budgetAlertThreshold: 80,
        notificationSettings: {
          budgetAlerts: true,
          weeklyDigest: true,
          savingTips: true,
        },
        city: 'Санкт-Петербург',
        notes: 'Фокус на спортпит, гречку, яйца и курицу по акциям',
        updatedAt: new Date().toISOString(),
      },
    },
  },
  {
    id: 'demo-family',
    title: 'Семья с детьми',
    subtitle: '55 000 ₽/мес • Баланс и польза',
    icon: '👨‍👩‍👧‍👦',
    user: {
      id: 'demo-user-2',
      name: 'Елена и Дмитрий',
      email: 'family.smart@budget.app',
      avatar: '👨‍🍳',
      avatarColor: 'from-amber-400 to-orange-500',
      createdAt: '2026-07-10',
      isOnboarded: true,
      profile: {
        currency: 'RUB',
        monthlyBudget: 55000,
        weeklyTarget: 13750,
        dailyTarget: 1833,
        adultsCount: 2,
        childrenCount: 2,
        petsCount: 0,
        dietaryPreferences: ['standard', 'healthy', 'lactose_free'],
        favoriteStores: ['perekrestok', 'vkusvill', 'lenta', 'kuper'],
        budgetGoal: 'smart_planning',
        budgetGoals: ['smart_planning', 'eat_healthier', 'reduce_waste'],
        budgetAlertThreshold: 75,
        notificationSettings: {
          budgetAlerts: true,
          weeklyDigest: true,
          savingTips: true,
        },
        city: 'Москва',
        notes: 'Большая закупка в гипермаркете по субботам + свежая молочка',
        updatedAt: new Date().toISOString(),
      },
    },
  },
  {
    id: 'demo-healthy',
    title: 'ЗОЖ и Правильное питание',
    subtitle: '38 000 ₽/мес • Свежие овощи и ВкусВилл',
    icon: '🥑',
    user: {
      id: 'demo-user-3',
      name: 'Мария Ветрова',
      email: 'maria.fit@budget.app',
      avatar: '🥑',
      avatarColor: 'from-emerald-400 to-teal-500',
      createdAt: '2026-08-20',
      isOnboarded: true,
      profile: {
        currency: 'RUB',
        monthlyBudget: 38000,
        weeklyTarget: 9500,
        dailyTarget: 1266,
        adultsCount: 1,
        childrenCount: 0,
        petsCount: 0,
        dietaryPreferences: ['healthy', 'vegetarian', 'gluten_free'],
        favoriteStores: ['vkusvill', 'samokat', 'perekrestok'],
        budgetGoal: 'eat_healthier',
        budgetGoals: ['eat_healthier', 'reduce_waste'],
        budgetAlertThreshold: 85,
        notificationSettings: {
          budgetAlerts: true,
          weeklyDigest: true,
          savingTips: false,
        },
        city: 'Казань',
        notes: 'Органические продукты, сезонные ягоды, микрозелень',
        updatedAt: new Date().toISOString(),
      },
    },
  },
];
